DROP TABLE IF EXISTS urls;
drop table if exists url_checks;

create TABLE urls (
  id                            bigint generated by default as identity not null,
  created_at                    timestamp not null,
  name                          varchar(255),
  constraint pk_url primary key (id)
);

create table url_checks (
  id                            bigint generated by default as identity not null,
  created_at                    timestamp not null,
  status_code                   int,
  title                         varchar(255),
  h1                            varchar(255),
  description                   varchar(255),
  url_id                        bigint not null,
  constraint pk_url_checks primary key (id)
);
